# Taps
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'

# Binaries
brew 'bash' # Latest Bash version
brew 'composer'
brew 'coreutils' # Those that come with macOS are outdated
brew 'ddev/ddev/ddev'
brew 'fastfetch'
brew 'gh'
brew 'git'
brew 'go'
brew 'grep'
brew 'has'
brew 'mkcert'
brew 'nss'
brew 'nvm'
brew 'pantheon-systems/external/terminus'
brew 'php'
brew 'pkg-config' # https://github.com/driesvints/dotfiles/issues/20
brew 'trash'

# Apps
cask 'appcleaner'
cask 'arc'
cask 'cursor'
cask 'discord'
cask 'ente-auth'
cask 'firefox'
cask 'google-chrome'
cask 'hiddenbar'
cask 'logi-options+'
cask 'monitorcontrol'
cask 'notion'
cask 'notion-calendar'
cask 'phpstorm'
cask 'postman'
cask 'raycast'
cask 'sequel-ace'
cask 'slack'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'vlc'
cask 'warp'
cask 'whatsapp'
cask 'zoom'

# Fonts
cask 'font-source-code-pro-for-powerline'
